org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official

# Compose Multiplatform
org.jetbrains.compose.experimental.uikit.enabled=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Version (updated by release process, used as fallback by F-Droid)
VERSION_CODE=69
VERSION_NAME=1.4.0
