org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official

# Compose Multiplatform
org.jetbrains.compose.experimental.uikit.enabled=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# F-Droid parseable version (auto-updated by release CI)
VERSION_CODE=73
VERSION_NAME=1.4.0
